%YAML:1.0

#--------------------------------------------------------------------------------------------
# LIDAR INFORMATION 
#--------------------------------------------------------------------------------------------
LidarType: "HDL-64E"

# Lidar Point cloud patch work
patchwork.verbose: 0   # To check effect of uprightness/elevation/flatness
patchwork.visualize: 0 # Ground Likelihood Estimation is visualized

# Ground Plane Fitting parameters
patchwork.GPF.sensor_height: 1.73
patchwork.GPF.num_iter: 3
patchwork.GPF.num_lpr: 20
patchwork.GPF.num_min_pts: 10
patchwork.GPF.th_seeds: 0.5
patchwork.GPF.th_dist: 0.125
patchwork.GPF.max_r: 80.0
patchwork.GPF.min_r: 2.7 # to consider vicinity of mobile plot form.
patchwork.GPF.uprightness_thr: 0.707 # For uprightness. 45: 0.707 / 60: 0.866. The larger, the more conservative
# The points below the adaptive_seed_selection_margin * sensor_height are filtered

patchwork.adaptive_seed_selection_margin: -1.1
patchwork.using_global_elevation: false
patchwork.global_elevation_threshold: -0.5
patchwork.uniform.num_rings: 16
patchwork.uniform.num_sectors: 54

# Note that `num_zones` == size of `num_sectors_each_zone` == size of `num_rings_each_zone` == size of `min_ranges` - 1
# To divide zones, max_r, min_r, and min_ranges are utilized
patchwork.czm.num_zones: 4
patchwork.czm.num_sectors_each_zone: [16, 32 ,54, 32]
patchwork.czm.num_rings_each_zone: [2, 4, 4, 4]
patchwork.czm.min_ranges_each_zone: [2.7, 12.3625, 22.025, 41.35]
patchwork.czm.elevation_thresholds:  [-1.2, -0.9984, -0.851, -0.605] # For elevation. The size should be equal to flatness_thresholds vector
patchwork.czm.flatness_thresholds:  [0.0, 0.000125, 0.000185, 0.000185]  # For flatness. The size should be equal to elevation_thresholds vector